name: gtm-dashboard
region: nyc
services:
  - name: backend
    github:
      repo: Saurabh272/gtm-dashboard
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: Dockerfile
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: DB_PORT
        value: ${db.PORT}
      - key: DB_USERNAME
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
      - key: DB_NAME
        value: ${db.DATABASE}
      - key: JWT_SECRET
        value: your-jwt-secret
      - key: DB_SSL
        value: "true"

  - name: frontend
    github:
      repo: your-github-username/your-repo-name
      branch: main
      deploy_on_push: true
    source_dir: client
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${APP_URL}

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database